<a href="https://colab.research.google.com/github/L-jsA/AULAS-GEN---GIT/blob/main/atividade8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1 - coleta de dados: receber as informações que podem vir de diversas fontes
# 2 - limpeza dos dados: remover informações não necessáriass (dados em branco, vazios, erros...)
# 3 - engenharia de atributos: com o que temos a fazer?
# 4 - treinar modelo
# 5 - testar o modelo

# sempre que trabalhamos com dados e com ml precisamos:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# bibliotecas genericas para dados

# vamos usar a biblioteca skleran para treinar e testar o modelo de previsão das notas
# existem métricas padrões que podemos utilizar:
# erro quadratico médio
# erro médio absoluto
# score

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df_notas = pd.read_excel("/content/Copy of BIG-DATA-05 - Predicting School Exam Scores.xlsx")
df_notas.head()

   Student ID  Study Hours  Homework Completed  Attendance Rate (%)  Exam Score
0         101          5.0                 1.0                   95        85.0
1         102          3.0                 0.0                   88        72.0
2         103          NaN                 1.0                  110        88.0
3         104          4.0                 NaN                   85         NaN
4         105          6.0                 1.0                  100        91.0

In [3]:
# compreender os dados
df_notas.info()
df_notas.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Student ID           8 non-null      int64
 1   Study Hours          6 non-null      float64
 2   Homework Completed   7 non-null      float64
 3   Attendance Rate (%)  8 non-null      int64
 4   Exam Score           7 non-null      float64
dtypes: float64(3), int64(2)
memory usage: 452.0 bytes

       Student ID  Study Hours  ...  Attendance Rate (%)  Exam Score
count     8.00000     6.000000  ...              8.00000    7.000000
mean    104.50000     4.166667  ...             93.00000   81.142857
std       2.44949     1.471960  ...              8.55236    9.081640
min     101.00000     2.000000  ...             85.00000   70.000000
25%     102.75000     3.250000  ...             87.25000   72.500000
50%     104.50000     4.500000  ...             90.50000   85.000000
75%     106.25000     5.000000  ...             96.25000   88.500000
max     108.00000     6.000000  ...            110.00000   91.000000

[8 rows x 5 columns]

In [4]:
# na limpeza você pode utilizar da média ou da exclusão dos dados
df_notas.isnull().sum()

# colocando a média
# tratando pelo tipo do dado
df_notas.fillna(df_notas.mean(numeric_only=True), inplace=True)

display(df_notas)

   Student ID  Study Hours  Homework Completed  Attendance Rate (%)  Exam Score
0         101     5.000000            1.000000                   95   85.000000
1         102     3.000000            0.000000                   88   72.000000
2         103     4.166667            1.000000                  110   88.000000
3         104     4.000000            0.714286                   85   81.142857
4         105     6.000000            1.000000                  100   91.000000
5         106     4.166667            1.000000                   92   73.000000
6         107     2.000000            0.000000                   89   70.000000
7         108     5.000000            1.000000                   85   89.000000

In [8]:
# corrigir dados invalidos ou errados
df_notas['Attendance Rate (%)'] = df_notas['Attendance Rate (%)'].clip(upper=100)
display(df_notas)

   Student ID  Study Hours  Homework Completed  Attendance Rate (%)  Exam Score
0         101     5.000000            1.000000                   95   85.000000
1         102     3.000000            0.000000                   88   72.000000
2         103     4.166667            1.000000                  100   88.000000
3         104     4.000000            0.714286                   85   81.142857
4         105     6.000000            1.000000                  100   91.000000
5         106     4.166667            1.000000                   92   73.000000
6         107     2.000000            0.000000                   89   70.000000
7         108     5.000000            1.000000                   85   89.000000

In [10]:
# engenharia de atributos
# o que temos de relevante?

# feature
caracteristicas = ["Study Hours", "Attendance Rate (%)"]
caracteristicas_notas = df_notas[caracteristicas]

# target
alvo = 'Exam Score'
alvo_notas = df_notas[alvo]

# o campo exam exore do excel ja tem resposta
# o campo Final exam score que criarmos vai prever as respostas

# em geral para os trabalhos divimos os dados para treino e teste

caracteristicas_notas_train, caracteristicas_notas_test, alvo_notas_train, alvo_notas_test = train_test_split(
    caracteristicas_notas, alvo_notas, test_size=0.2, random_state=42
)

In [12]:
# treinar o modelo
modelo = LinearRegression()
modelo.fit(caracteristicas_notas_train, alvo_notas_train)

LinearRegression()

In [14]:
# tentar fazer uma previsão de dados
alvo_notas_previsao = modelo.predict(caracteristicas_notas_test)
print(alvo_notas_previsao)

[76.71116949 83.00702749]

In [18]:
# inserir casos para o sistema
# criar uma comparaçào

comparacao = pd.DataFrame({
    "Notal real": alvo_notas_test.values,
    "Previsao de nota": alvo_notas_previsao
})
comparacao.head()

novo_aluno = pd.DataFrame({
    "Study Hours": [5],
    "Attendance Rate (%)": [70]
})

nota_previsao = modelo.predict(novo_aluno)
print(f'{nota_previsao}')

[85.07843661]