<a href="https://colab.research.google.com/github/L-jsA/AULAS-GEN---GIT/blob/main/atividade3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

# Carregamento de dados

In [4]:
df_carbon_offsets = pd.read_csv('/content/carbon_offsets.csv')
df_customers_data= pd.read_csv('/content/customers_data.csv')
df_rentals_data = pd.read_json('/content/rentals_data.json')
df_vehicles_data = pd.read_json('/content/vehicles_data.json')

In [12]:
df_carbon_offsets.info()
df_carbon_offsets.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   year                2 non-null      int64
 1   carbon_offset_tons  2 non-null      int64
 2   cost_usd            2 non-null      int64
dtypes: int64(3)
memory usage: 180.0 bytes

   year  carbon_offset_tons  cost_usd
0  2023                 120      1800
1  2024                 200      3000

In [13]:
df_customers_data.info()
df_customers_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    4 non-null      object
 1   customer_type  4 non-null      object
 2   age            3 non-null      float64
 3   city           4 non-null      object
 4   loyalty_score  4 non-null      int64
dtypes: float64(1), int64(1), object(3)
memory usage: 292.0+ bytes

  customer_id customer_type   age       city  loyalty_score
0        C001    Recorrente  35.0  São Paulo             90
1        C002          Novo  28.0   Curitiba             60
2        C003          Novo   NaN   Salvador             50
3        C004   Corporativo  45.0  São Paulo             95

In [14]:
df_rentals_data.info()
df_rentals_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rental_id    5 non-null      int64
 1   customer_id  5 non-null      object
 2   vehicle_id   5 non-null      object
 3   start_date   5 non-null      object
 4   end_date     5 non-null      object
 5   city         5 non-null      object
 6   daily_rate   5 non-null      int64
 7   distance_km  5 non-null      int64
dtypes: int64(3), object(5)
memory usage: 452.0+ bytes

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180,320
1,2002,C002,V101,2024/01/10,2024/01/12,Curitiba,150,210
2,2003,C003,V102,invalid_date,2024-01-15,Salvador,220,0
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300,980
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,-100,120

In [15]:
df_vehicles_data.info()
df_vehicles_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   vehicle_id    5 non-null      object
 1   model         5 non-null      object
 2   fuel_type     5 non-null      object
 3   co2_g_per_km  4 non-null      float64
 4   category      5 non-null      object
dtypes: float64(1), object(4)
memory usage: 332.0+ bytes

  vehicle_id          model fuel_type  co2_g_per_km   category
0       V100           HB20  Gasolina         120.0  Econômico
1       V101        Corolla  Gasolina         160.0      Sedan
2       V102        Compass    Diesel         180.0        SUV
3       V103  Tesla Model 3  Elétrico           0.0   Elétrico
4       V104           Onix  Gasolina           NaN  Econômico

1. customers --> age --> valor ausente
2. rentals --> daily_rate com valor < 0
3. vehicles --> co2_g_per_km dados ausente
4. rentals --> daily_rate está como string
5. rentals --> data inválida
6. rentals --> data com formatação diferente

In [18]:
# customers --> age --> valor ausente

# Idade ausente
media_idade = df_customers_data['age'].mean()

df_customers_data['age'] = df_customers_data['age'].fillna(media_idade)

display(df_customers_data)

  customer_id customer_type   age       city  loyalty_score
0        C001    Recorrente  35.0  São Paulo             90
1        C002          Novo  28.0   Curitiba             60
2        C003          Novo  36.0   Salvador             50
3        C004   Corporativo  45.0  São Paulo             95

In [19]:
# rentals --> daily_rate com valor < 0
df_rentals_data.loc[df_rentals_data['daily_rate']<=0, 'daily_rate'] = pd.NA
display(df_rentals_data)

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320
1,2002,C002,V101,2024/01/10,2024/01/12,Curitiba,150.0,210
2,2003,C003,V102,invalid_date,2024-01-15,Salvador,220.0,0
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120

In [27]:
# vehicles --> co2_g_per_km dados ausente

df_vehicles_data['co2_g_per_km'] = df_vehicles_data['co2_g_per_km'].fillna(120)

display(df_vehicles_data)

  vehicle_id          model fuel_type  co2_g_per_km   category
0       V100           HB20  Gasolina         120.0  Econômico
1       V101        Corolla  Gasolina         160.0      Sedan
2       V102        Compass    Diesel         180.0        SUV
3       V103  Tesla Model 3  Elétrico           0.0   Elétrico
4       V104           Onix  Gasolina         115.0  Econômico

In [23]:
# rentals --> daily_rate está como string
df_rentals_data['daily_rate'] = pd.to_numeric(df_rentals_data['daily_rate'], errors='coerce')
display(df_rentals_data)

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320
1,2002,C002,V101,2024/01/10,2024/01/12,Curitiba,150.0,210
2,2003,C003,V102,invalid_date,2024-01-15,Salvador,220.0,0
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120

In [28]:
# rentals --> data inválida
df_rentals_data['start_date'] = pd.to_datetime(df_rentals_data['start_date'], errors = 'coerce')
df_rentals_data['end_date'] = pd.to_datetime(df_rentals_data['end_date'], errors = 'coerce')
print('quantidade de dados truncados') # Exibe uma mensagem no console
print(df_rentals_data['start_date'].isna().sum()) # Conta e mostra quantas datas ficaram inválidas/nulas após a conversão.

display(df_rentals_data)

quantidade de dados truncados
2

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320
1,2002,C002,V101,NaT,NaT,Curitiba,150.0,210
2,2003,C003,V102,NaT,2024-01-15,Salvador,220.0,0
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120

In [ ]:
# rentals --> data com formatação diferente

In [29]:
# Criar backup de dados
df_carbon_clean = df_carbon_offsets
df_rentals_clean = df_rentals_data
df_customer_clean = df_customers_data
df_vehicles_clean = df_vehicles_data

In [39]:
# Calcule a duração de cada locação (em dias)
df_rentals_clean['dias_locação'] = (
    df_rentals_clean['end_date'] - df_rentals_clean['start_date']
).dt.days

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km,dias_locação
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320,3.0
1,2002,C002,V101,NaT,NaT,Curitiba,150.0,210,NaN
2,2003,C003,V102,NaT,2024-01-15,Salvador,220.0,0,NaN
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980,9.0
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120,1.0

In [43]:
# Calcule a receita total por locação
# Valor da diária = daily_rate

# dias de locação * valor da diária
df_rentals_clean['receita_total'] = df_rentals_clean['dias_locação'] * df_rentals_clean['daily_rate']
display(df_rentals_clean)

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km,dias_locação,receita_total
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320,3.0,540.0
1,2002,C002,V101,NaT,NaT,Curitiba,150.0,210,NaN,NaN
2,2003,C003,V102,NaT,2024-01-15,Salvador,220.0,0,NaN,NaN
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980,9.0,2700.0
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120,1.0,NaN

In [44]:
# Faça o merge com a base de veículos

df_consolidado = df_rentals_clean.merge(df_vehicles_clean, on='vehicle_id')
df_conslidado = df_consolidado.merge(df_customer_clean, on='customer_id')

display(df_consolidado)

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km,dias_locação,receita_total,model,fuel_type,co2_g_per_km,category
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320,3.0,540.0,HB20,Gasolina,120.0,Econômico
1,2002,C002,V101,NaT,NaT,Curitiba,150.0,210,NaN,NaN,Corolla,Gasolina,160.0,Sedan
2,2003,C003,V102,NaT,2024-01-15,Salvador,220.0,0,NaN,NaN,Compass,Diesel,180.0,SUV
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980,9.0,2700.0,Tesla Model 3,Elétrico,0.0,Elétrico
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120,1.0,NaN,Onix,Gasolina,115.0,Econômico

In [46]:
# Calcule a emissão de CO2 por locação
df_consolidado['co2_emitido'] = df_conslidado['co2_g_per_km'] * df_conslidado['distance_km']
display(df_consolidado)

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km,dias_locação,receita_total,model,fuel_type,co2_g_per_km,category,co2_emitido
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320,3.0,540.0,HB20,Gasolina,120.0,Econômico,38400.0
1,2002,C002,V101,NaT,NaT,Curitiba,150.0,210,NaN,NaN,Corolla,Gasolina,160.0,Sedan,33600.0
2,2003,C003,V102,NaT,2024-01-15,Salvador,220.0,0,NaN,NaN,Compass,Diesel,180.0,SUV,0.0
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980,9.0,2700.0,Tesla Model 3,Elétrico,0.0,Elétrico,0.0
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120,1.0,NaN,Onix,Gasolina,115.0,Econômico,13800.0

In [47]:
# Extraia ano e o mês da data de inicio de locação
# para extrair informações da data temos:
# .dt.days - dia
# .dt.month - mês
# .dt.year - ano
# .dt.weekday - dia do mês

df_consolidado['mes'] = df_consolidado['start_date'].dt.month
df_consolidado['ano'] = df_consolidado['start_date'].dt.year
df_consolidado['dia_da_semana'] = df_consolidado['start_date'].dt.weekday

display(df_consolidado)

,rental_id,customer_id,vehicle_id,start_date,end_date,city,daily_rate,distance_km,dias_locação,receita_total,model,fuel_type,co2_g_per_km,category,co2_emitido,mes,ano,dia_da_semana
0,2001,C001,V100,2024-01-05,2024-01-08,São Paulo,180.0,320,3.0,540.0,HB20,Gasolina,120.0,Econômico,38400.0,1.0,2024.0,4.0
1,2002,C002,V101,NaT,NaT,Curitiba,150.0,210,NaN,NaN,Corolla,Gasolina,160.0,Sedan,33600.0,NaN,NaN,NaN
2,2003,C003,V102,NaT,2024-01-15,Salvador,220.0,0,NaN,NaN,Compass,Diesel,180.0,SUV,0.0,NaN,NaN,NaN
3,2004,C004,V103,2024-02-01,2024-02-10,São Paulo,300.0,980,9.0,2700.0,Tesla Model 3,Elétrico,0.0,Elétrico,0.0,2.0,2024.0,3.0
4,2005,C001,V104,2024-02-15,2024-02-16,Rio de Janeiro,NaN,120,1.0,NaN,Onix,Gasolina,115.0,Econômico,13800.0,2.0,2024.0,3.0

# Identificação de dados



*   Datas;
*   Valores negativos
*   DataTypes

# Correções